(self.__BUILD_MANIFEST = (function (
  s,
  e,
  a,
  t,
  c,
  i,
  n,
  d,
  u,
  h,
  r,
  o,
  l,
  k,
  b,
  g,
  f,
  p,
  j,
  m,
  v,
  y,
  w,
  _,
  z,
  q,
  x,
  I,
  N,
  B,
  F,
  A,
  D,
  S,
  E,
  L,
  M,
  T,
  U,
  C,
  H,
  R,
  P,
  G,
  J,
  K,
  O,
  Q,
  V
) {
  return {
    __rewrites: {
      afterFiles: [
        {
          has: [
            { type: r, key: 'o', value: S },
            { type: r, key: 'p', value: L },
            { type: r, key: 'r', value: '(?<region>[a-z]{2})' },
          ],
          source: M,
          destination: T,
        },
        {
          has: [
            { type: r, key: 'o', value: S },
            { type: r, key: 'p', value: L },
          ],
          source: M,
          destination: T,
        },
      ],
      beforeFiles: [],
      fallback: [],
    },
    __routerFilterStatic: { numItems: 0, errorRate: 1e-4, numBits: 0, numHashes: C, bitArray: [] },
    __routerFilterDynamic: { numItems: m, errorRate: 1e-4, numBits: m, numHashes: C, bitArray: [] },
    '/': [s, e, a, t, H, 'static/chunks/pages/index-f2c3687019d09f22.js'],
    '/_error': ['static/chunks/pages/_error-732bedd774215ddc.js'],
    '/account': [s, e, a, t, 'static/chunks/pages/account-c27456a490421732.js'],
    '/activitystats/[server_id]': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/activitystats/[server_id]-ca7dbb6daa30ad89.js',
    ],
    '/add-community-server': [
      s,
      e,
      a,
      c,
      t,
      'static/chunks/pages/add-community-server-1d316144a43ddefd.js',
    ],
    '/add-question': [s, e, a, i, t, _, 'static/chunks/pages/add-question-86a8b880f43cc01a.js'],
    '/ai-experiments': [s, e, a, n, u, t, 'static/chunks/pages/ai-experiments-662afc508f85d3a1.js'],
    '/ai-experiments/[experimentId]': [
      s,
      e,
      a,
      c,
      i,
      z,
      R,
      'static/chunks/5254-0033dffe5713c1c7.js',
      t,
      P,
      'static/chunks/pages/ai-experiments/[experimentId]-2aeef19cfa9c2152.js',
    ],
    '/ai-playground': [s, e, a, c, t, 'static/chunks/pages/ai-playground-3bf6fb51c77d79fd.js'],
    '/analytics': [s, e, a, n, u, h, o, l, t, 'static/chunks/pages/analytics-6795592d04cb0c73.js'],
    '/answerauthors/[server_id]': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/answerauthors/[server_id]-6ea37fd9ce028524.js',
    ],
    '/botactivity': [s, e, a, t, 'static/chunks/pages/botactivity-8c4963cc211c71ed.js'],
    '/botguilds': [
      s,
      e,
      a,
      n,
      k,
      'static/chunks/6653-b1c675ce78d7a631.js',
      t,
      'static/chunks/pages/botguilds-037e47763509345f.js',
    ],
    '/botguilds98347yhr983hf': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/botguilds98347yhr983hf-544510e6cffb6d45.js',
    ],
    '/botmessages': [
      s,
      e,
      a,
      n,
      d,
      u,
      l,
      'static/chunks/1271-85fb9d2d6ffc3089.js',
      t,
      G,
      'static/chunks/pages/botmessages-3b38668fad0b187e.js',
    ],
    '/channel-config': [s, e, a, t, v, 'static/chunks/pages/channel-config-6d68666ed7b0a270.js'],
    '/chat-widget': [
      b,
      g,
      s,
      e,
      c,
      i,
      d,
      f,
      y,
      p,
      w,
      q,
      'static/chunks/pages/chat-widget-b6a4f6d764e26ef0.js',
    ],
    '/chat-widget-test': [
      s,
      e,
      a,
      'static/chunks/4947-c6fd72593852bf99.js',
      t,
      'static/chunks/pages/chat-widget-test-439d1b16f42220a9.js',
    ],
    '/create-community': [
      s,
      e,
      a,
      c,
      t,
      'static/chunks/pages/create-community-54a810ea1ceb83e9.js',
    ],
    '/edit-question': [s, e, a, i, t, _, 'static/chunks/pages/edit-question-e802e62d74d260eb.js'],
    '/edit-source-item': [
      s,
      e,
      a,
      i,
      t,
      _,
      'static/chunks/pages/edit-source-item-5e5b068d1b7d558b.js',
    ],
    '/edit-web-pages': [s, e, a, t, 'static/chunks/pages/edit-web-pages-9c7499885050f8a2.js'],
    '/email-integration': [
      s,
      e,
      a,
      c,
      'static/chunks/8402-fd8fb72ffed66e03.js',
      t,
      'static/chunks/pages/email-integration-cab392647f164eff.js',
    ],
    '/escalation-agent/ai-workflows': [
      s,
      e,
      a,
      n,
      k,
      t,
      'static/chunks/pages/escalation-agent/ai-workflows-ccc068de63577638.js',
    ],
    '/escalation-agent/chat-history': [
      s,
      e,
      a,
      c,
      i,
      z,
      R,
      t,
      P,
      'static/chunks/pages/escalation-agent/chat-history-40bd96b642ae20e6.js',
    ],
    '/escalation-templates': [
      s,
      e,
      a,
      x,
      t,
      'static/chunks/pages/escalation-templates-3c2c9bcb26b83811.js',
    ],
    '/experiments': [
      s,
      e,
      a,
      c,
      n,
      j,
      k,
      z,
      'static/chunks/7626-33b0250fd22deb93.js',
      t,
      G,
      'static/chunks/pages/experiments-0e3dd299afaa5172.js',
    ],
    '/faqinsights': [s, e, a, n, u, l, t, 'static/chunks/pages/faqinsights-b6fb52ab77dfeeb2.js'],
    '/faqinsights/[server_id]': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/faqinsights/[server_id]-045d1daf382f54cc.js',
    ],
    '/feedback-success': [s, e, a, t, 'static/chunks/pages/feedback-success-8e8cec85e122b5a4.js'],
    '/generative-answers': ['static/chunks/pages/generative-answers-181f2e713b18140e.js'],
    '/getting-started': [
      s,
      e,
      a,
      J,
      'static/chunks/1146-f1982fc093e0eabc.js',
      t,
      v,
      I,
      'static/chunks/pages/getting-started-ac910163f1959e77.js',
    ],
    '/groups': [s, e, a, d, t, 'static/chunks/pages/groups-2850c3e140de90a5.js'],
    '/healthz': ['static/chunks/pages/healthz-7cb26e13c288a141.js'],
    '/home': [s, e, a, t, H, 'static/chunks/pages/home-385d29149d4341b2.js'],
    '/imprint': ['static/chunks/pages/imprint-55b6cb7f4690eb87.js'],
    '/installation/authorize-jira-integration': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/authorize-jira-integration-281f292512c85680.js',
    ],
    '/installation/authorize-slack-integration': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/authorize-slack-integration-59f25ec4261a9f47.js',
    ],
    '/installation/authorize-zendesk-messaging': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/authorize-zendesk-messaging-36e6d9205a76d0e2.js',
    ],
    '/installation/fail': [s, e, a, t, 'static/chunks/pages/installation/fail-65210f4cc5ac49ad.js'],
    '/installation/jira-auth-token': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/jira-auth-token-9f27eb7e6f7355d2.js',
    ],
    '/installation/onboarding-overview': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/onboarding-overview-f7494033f2b7d1fa.js',
    ],
    '/installation/set-up-jira-internal-channel': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/set-up-jira-internal-channel-40a711b67f576209.js',
    ],
    '/installation/set-up-slack-internal-channel': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/set-up-slack-internal-channel-4e2953722bbe5357.js',
    ],
    '/installation/success': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/success-a7b1f02b8a00ba32.js',
    ],
    '/installation/sunshine-conversations-integrations-fields': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/sunshine-conversations-integrations-fields-99c72d67e20d52c0.js',
    ],
    '/installation/zendesk-app': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/installation/zendesk-app-0531d0a13a3d24ac.js',
    ],
    '/internal': [s, e, a, c, t, 'static/chunks/pages/internal-7a35fb29a262bcc0.js'],
    '/join': ['static/chunks/pages/join-023ad509cab475b3.js'],
    '/knowledge-hub': [s, e, a, t, 'static/chunks/pages/knowledge-hub-a1be20e7f70f6f1d.js'],
    '/knowledge-hub/knowledge-base': [
      s,
      e,
      a,
      K,
      t,
      O,
      'static/chunks/pages/knowledge-hub/knowledge-base-96090a0a2600b262.js',
    ],
    '/knowledge-hub/knowledge-base/community-channels': [
      s,
      e,
      a,
      t,
      v,
      I,
      'static/chunks/pages/knowledge-hub/knowledge-base/community-channels-745aee3d01de53d8.js',
    ],
    '/knowledge-hub/knowledge-base/search': [
      s,
      e,
      a,
      K,
      t,
      O,
      'static/chunks/pages/knowledge-hub/knowledge-base/search-8bdef319b3faa2d7.js',
    ],
    '/live-chat': [
      b,
      g,
      s,
      e,
      a,
      i,
      d,
      h,
      o,
      f,
      x,
      'static/chunks/6635-0070b03435eb8650.js',
      t,
      p,
      'static/chunks/pages/live-chat-c074ab2219e767aa.js',
    ],
    '/live-chat/macros': [
      s,
      e,
      a,
      i,
      t,
      'static/chunks/pages/live-chat/macros-57592195e4363dcd.js',
    ],
    '/live-chat/macros/new-macro': [
      s,
      e,
      a,
      i,
      t,
      'static/chunks/pages/live-chat/macros/new-macro-f149110eba3aa26b.js',
    ],
    '/live-chat/macros/[macroId]': [
      s,
      e,
      a,
      i,
      t,
      'static/chunks/pages/live-chat/macros/[macroId]-3e0dd1e4f6d2e3f0.js',
    ],
    '/live-chat/stresstest': [
      b,
      g,
      s,
      e,
      a,
      c,
      i,
      d,
      f,
      y,
      'static/chunks/4425-806aa3c16b39af1c.js',
      t,
      p,
      w,
      q,
      'static/chunks/pages/live-chat/stresstest-8a2726649345716e.js',
    ],
    '/live-chat/test-open-single-ticket': [
      b,
      g,
      s,
      e,
      a,
      c,
      i,
      d,
      f,
      y,
      t,
      p,
      w,
      q,
      'static/chunks/pages/live-chat/test-open-single-ticket-542762c24616ad88.js',
    ],
    '/members': [s, e, a, x, t, 'static/chunks/pages/members-e15eed1dbfd5bfb5.js'],
    '/my-sentry-test': ['static/chunks/pages/my-sentry-test-a41c41756affe67c.js'],
    '/privacy': ['static/chunks/pages/privacy-25a20a0b19630aeb.js'],
    '/question-list': [s, e, a, t, 'static/chunks/pages/question-list-b85cd2967f7b292c.js'],
    '/reporting': [
      s,
      e,
      a,
      n,
      u,
      h,
      o,
      l,
      'static/chunks/9449-2e416076bceb274e.js',
      t,
      'static/chunks/pages/reporting-ef5f099ffab9be61.js',
    ],
    '/roles': [
      s,
      e,
      a,
      c,
      j,
      'static/chunks/6280-8e656166763326e9.js',
      t,
      'static/chunks/pages/roles-e83a693a3a669234.js',
    ],
    '/scrapeddocs': [s, e, a, t, 'static/chunks/pages/scrapeddocs-4b06ac5e0e4799e0.js'],
    '/send-dm': [
      s,
      e,
      a,
      c,
      'static/chunks/430-64c7115857798e23.js',
      t,
      Q,
      'static/chunks/pages/send-dm-b36ad82e8244d2de.js',
    ],
    '/settings': [s, e, a, d, t, v, I, 'static/chunks/pages/settings-a5d0ed4aaeb24ffa.js'],
    '/simlinks': [s, e, a, t, 'static/chunks/pages/simlinks-9519b33e77e4e1c1.js'],
    '/simulation/[experimentName]': [
      s,
      e,
      a,
      n,
      k,
      t,
      'static/chunks/pages/simulation/[experimentName]-556a2fb0ccc07bcc.js',
    ],
    '/sources/[sourceName]': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/sources/[sourceName]-f14fa8ccb3f15fef.js',
    ],
    '/stats': [
      N,
      s,
      e,
      a,
      c,
      h,
      o,
      j,
      B,
      F,
      t,
      A,
      V,
      'static/chunks/pages/stats-52f7a293c7ee0d35.js',
    ],
    '/stats/all': [
      N,
      s,
      e,
      a,
      c,
      j,
      B,
      F,
      t,
      A,
      'static/chunks/pages/stats/all-c83338501fdded75.js',
    ],
    '/stats/community': [
      s,
      e,
      a,
      c,
      h,
      o,
      j,
      B,
      t,
      V,
      'static/chunks/pages/stats/community-df289fe813294436.js',
    ],
    '/stats/shortterm': [
      N,
      s,
      e,
      a,
      F,
      'static/chunks/6022-ee304b92c778beca.js',
      t,
      A,
      'static/chunks/pages/stats/shortterm-f60042293998ed3f.js',
    ],
    '/subscribercounts98347yhr983hf': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/subscribercounts98347yhr983hf-599f867a40af7e6d.js',
    ],
    '/support-portal': [
      s,
      e,
      a,
      d,
      J,
      'static/chunks/3824-9783bbfeb884d9d4.js',
      t,
      Q,
      'static/chunks/pages/support-portal-2cf369bff2ff04d1.js',
    ],
    '/telegram-verification': [
      s,
      e,
      a,
      c,
      t,
      'static/chunks/pages/telegram-verification-36ad04a49f6ee7db.js',
    ],
    '/terms': ['static/chunks/pages/terms-8d177332c2fe752b.js'],
    '/test': [s, e, a, t, 'static/chunks/pages/test-c852936d1fba46d1.js'],
    '/test-streaming': ['static/chunks/pages/test-streaming-6a4cfa96bba1b8ba.js'],
    '/translate-announcement': ['static/chunks/pages/translate-announcement-eb416168d7c0c4ff.js'],
    '/web-chat/history': [
      s,
      e,
      a,
      c,
      i,
      n,
      d,
      u,
      l,
      y,
      t,
      p,
      w,
      'static/chunks/pages/web-chat/history-3a7ca18ee4e8d6af.js',
    ],
    '/web-pages': [s, e, a, n, k, t, 'static/chunks/pages/web-pages-00f8a5124eb6aded.js'],
    '/zendesk/iframe': [
      b,
      g,
      s,
      h,
      f,
      'static/css/ff017d06655a25da.css',
      'static/chunks/6754-268b13eb19cd007a.js',
      'static/chunks/pages/zendesk/iframe-0bae6aa3fa64bc28.js',
    ],
    '/zendesk/installation': [
      s,
      e,
      a,
      t,
      'static/chunks/pages/zendesk/installation-1400ceb34618c969.js',
    ],
    '/zendesk/signup': [s, e, a, t, 'static/chunks/pages/zendesk/signup-51d8ab6fcfd7411a.js'],
    sortedPages: [
      '/',
      '/_app',
      '/_error',
      '/account',
      '/activitystats/[server_id]',
      '/add-community-server',
      '/add-question',
      '/ai-experiments',
      '/ai-experiments/[experimentId]',
      '/ai-playground',
      '/analytics',
      '/answerauthors/[server_id]',
      '/botactivity',
      '/botguilds',
      '/botguilds98347yhr983hf',
      '/botmessages',
      '/channel-config',
      '/chat-widget',
      '/chat-widget-test',
      '/create-community',
      '/edit-question',
      '/edit-source-item',
      '/edit-web-pages',
      '/email-integration',
      '/escalation-agent/ai-workflows',
      '/escalation-agent/chat-history',
      '/escalation-templates',
      '/experiments',
      '/faqinsights',
      '/faqinsights/[server_id]',
      '/feedback-success',
      '/generative-answers',
      '/getting-started',
      '/groups',
      '/healthz',
      '/home',
      '/imprint',
      '/installation/authorize-jira-integration',
      '/installation/authorize-slack-integration',
      '/installation/authorize-zendesk-messaging',
      '/installation/fail',
      '/installation/jira-auth-token',
      '/installation/onboarding-overview',
      '/installation/set-up-jira-internal-channel',
      '/installation/set-up-slack-internal-channel',
      '/installation/success',
      '/installation/sunshine-conversations-integrations-fields',
      '/installation/zendesk-app',
      '/internal',
      '/join',
      '/knowledge-hub',
      '/knowledge-hub/knowledge-base',
      '/knowledge-hub/knowledge-base/community-channels',
      '/knowledge-hub/knowledge-base/search',
      '/live-chat',
      '/live-chat/macros',
      '/live-chat/macros/new-macro',
      '/live-chat/macros/[macroId]',
      '/live-chat/stresstest',
      '/live-chat/test-open-single-ticket',
      '/members',
      '/my-sentry-test',
      '/privacy',
      '/question-list',
      '/reporting',
      '/roles',
      '/scrapeddocs',
      '/send-dm',
      '/settings',
      '/simlinks',
      '/simulation/[experimentName]',
      '/sources/[sourceName]',
      '/stats',
      '/stats/all',
      '/stats/community',
      '/stats/shortterm',
      '/subscribercounts98347yhr983hf',
      '/support-portal',
      '/telegram-verification',
      '/terms',
      '/test',
      '/test-streaming',
      '/translate-announcement',
      '/web-chat/history',
      '/web-pages',
      '/zendesk/iframe',
      '/zendesk/installation',
      '/zendesk/signup',
    ],
  };
})(
  'static/chunks/8894-5965ec1550e6a6fa.js',
  'static/chunks/838-88d982dea2bbc0d5.js',
  'static/chunks/2379-72aa9951a6ef5a3a.js',
  'static/chunks/4917-3e9a79f389691dd7.js',
  'static/chunks/1093-e09ebc8493997bd8.js',
  'static/chunks/5355-ab798e88f1d7e192.js',
  'static/chunks/7964-62bf932a986c1c2c.js',
  'static/chunks/2053-fa3de327d10b455a.js',
  'static/chunks/8021-b36387ebf4f15d73.js',
  'static/chunks/3172-c44ae0b8b22caed7.js',
  'query',
  'static/chunks/5251-489f5c4962968d3d.js',
  'static/chunks/272-14995a8a4eed7fc8.js',
  'static/chunks/865-55958b794c606c84.js',
  'static/chunks/7e42aecb-ddb6dca04023641b.js',
  'static/chunks/0bd2f4cc-53509fa621707033.js',
  'static/chunks/3953-dfe7d41af772bd01.js',
  'static/chunks/9940-210453ef7d44d198.js',
  'static/chunks/1522-caf77439b1c681d4.js',
  0,
  'static/chunks/8174-3d24741513f810c2.js',
  'static/chunks/7515-3c1bbcd1e5384d0d.js',
  'static/chunks/2021-1a7ba72330ab4845.js',
  'static/chunks/4800-0f09b738af616c5b.js',
  'static/chunks/230-b42af4979a685e6a.js',
  'static/chunks/4452-e8dbe8ceb8112b86.js',
  'static/chunks/7740-6e8dc84a0a3e6e15.js',
  'static/chunks/6885-5e03e563e156aee7.js',
  'static/chunks/6d2b60a9-8c831fc3314bb6e6.js',
  'static/chunks/2686-86c4a9eb44a07d45.js',
  'static/chunks/8019-456c01d63dfd65ad.js',
  'static/chunks/7665-28e11fe7424f0b9d.js',
  'o',
  '(?<orgid>\\d*)',
  'p',
  '(?<projectid>\\d*)',
  '/monitoring(/?)',
  void 0,
  1e-4,
  NaN,
  'static/chunks/2171-eebd1d6ea60d5e91.js',
  'static/chunks/8252-283f2012924de919.js',
  'static/chunks/3445-feb4b39eb11f493f.js',
  'static/chunks/3164-adc6dd6b1f46598a.js',
  'static/chunks/2199-c26d359e1c0f679a.js',
  'static/chunks/3654-471776015f1eb616.js',
  'static/chunks/7466-5ff07f55345d27a9.js',
  'static/chunks/2405-bc05e68c4cbb32a9.js',
  'static/chunks/2749-9b9a62f4a72a1aa6.js'
)),
  self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
